# Dockerized dev database
version: "3"

services:
  postgres:
    image: postgres
    container_name: ${DB_CONTAINER_NAME:-postgres-final-forum}
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
